#!/bin/bash

array=()
name=""
directory="."
maxdepth=0

function open {
	printf "File chosen: ${array[$1]}\nOpening file...\n"
    ${EDITOR:-vim} "${array[$1]}"
}

function f_print {
	p=1
	for i in ${array[@]}; do
		printf "$p | %s\n" "$i"
		p=$((p+1))
	done
	printf "What file would you like to open? (Enter a number): "
}

function getWantedFile {
	f_print
	while read c; do
		if [ $c -gt ${#array[*]} ]; then
			printf "That is not a valid number! (The numbers only go up to ${#array[*]})"
		else
			open $(($c - 1))
			break;
		fi
	done
}

function findFiles {
	if [ maxdepth != 0 ]; then
		while IFS=  read -r -d $'\0'; do
			if [ ${REPLY:0:2} = "./" ]; then reply=${REPLY:2}; fi
			if [ ! -d ${reply} ]; then array+=("$reply"); fi
		done < <(find $directory -maxdepth $maxdepth -name *$name* -print0)
	else
		while IFS=  read -r -d $'\0'; do
            if [ ${REPLY:0:1} -eq "./" ]; then reply=${REPLY:2}; fi
			if [ ! -d ${reply} ]; then array+=("$reply"); fi
		done < <(find $directory -name $name -print0)
	fi
}

if [ $# = 0 ]; then
	printf 'usage: fe [-n] [-d] [-m]'
	printf 'fe searches in subdirectories (unless -m is < 2)'
	exit
fi
while [ $# != 0 ]; do
	case "$1" in
		"-n")
			if [ ! -z $2 ]; then
				name="$2"
				shift
			fi
			shift
			;;
		"-d")
			if [ ! -z $2 ]; then
				directory="$2"
				shift
			fi
			shift
			;;
		"-m")
			if [ ! -z $2 ]; then
				maxdepth=$2
				shift
			fi
			shift
			;;
		*)
			echo "Illegal option -- $1"
			exit
			;;
	esac
done

findFiles
if [ ${#array[*]} -eq 0 ]; then
	printf "no files found!\n"
	exit
elif [ ${#array[*]} -eq 1 ]; then
	printf "only one file found: ${array[0]}\n"
	open "0"
else
	getWantedFile
fi
