#!/bin/bash

array=()
name=""
directory="."
maxdepth=0

function open {
	printf "File chosen: ${array[$1]}\nOpening file...\n"
	${EDITOR:-vi} "${array[$1]}"
}

function f_print {
	p=1
	for i in ${array[@]}; do
		printf "$p | %s\n" "$i"
		p=$((p+1))
	done
	printf "What file would you like to open? (Enter a number): "
}

function getWantedFile {
	f_print
	while read c; do
		if [ $c -gt ${#array[*]} ]; then
			printf "That is not a valid number! (The numbers only go up to ${#array[*]})"
		else
			open $(($c - 1))
			break;
		fi
	done
}

function findFiles {
	echo $name $directory $maxdepth
	if [ maxdepth != 0 ]; then
		while IFS=  read -r -d $'\0'; do
			array+=("$REPLY")
		done < <(find $directory -name "*$name*" -maxdepth "$maxdepth" -print0)
	else
		while IFS=  read -r -d $'\0'; do
			if [ ${REPLY:0:2} -eq "./"]; then
				$REPLY = $(echo $REPLY cut -c 3-)
			fi
			array+=("$REPLY")
		done < <(find $directory -name "$name" -print0)
	fi
	printf "${array[*]}\n"
}

if [ $# = 0 ]; then
	printf 'usage: fe [-n] [-d] [-md]'
	printf 'fe searches in subdirectories (unless -md is < 2)'
	exit
fi
while [ $# != 0 ]; do
	case "$1" in
		"-n")
			if [ ! -z $2 ]; then
				name="$2"
				shift
			fi
			shift
			;;
		"-d")
			if [ ! -z $2 ]; then
				directory="$2"
				shift
			fi
			shift
			;;
		"-md")
			if [ ! -z $2 ]; then
				maxdepth=$2
				shift
			fi
			shift
			;;
		*)
			echo "Illegal option -- $1"
			exit
			;;
	esac
done

findFiles
if [ ${#array[*]} -eq 0 ]; then
	printf "no files found!\n"
	exit
elif [ ${#array[*]} -eq 1 ]; then
	printf "only one file found: ${array[0]}\n"
	open "0"
else
	getWantedFile
fi
