#!/bin/bash

if [ ! $# = 1 ]; then
    printf "Usage - tab <number>\n"
    exit
fi

case $@ in
    "--help")
        printf "tab: echos a barrier of new lines\n"
        printf "Usage - tab <number>\n"
        printf "<number> is the number of new lines\n"
        shift
        ;;
    *[0-9]*)
		i=1
		while [ $i -lt $1 ]; do
			printf "\n"
			((i++))
			done
			shift
        ;;
    *)
        printf "Unknown argument - $1\n"
        exit
        ;;
esac
